version: "3.9"
services:

  db:
    image: postgres:13.9-alpine
    container_name: 'epic_postgres'
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/init_pg.sh:/docker-entrypoint-initdb.d/init_pg.sh
    healthcheck:
      test: PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER $POSTGRES_DB -c '\q'
      interval: 50s
      timeout: 10s
      retries: 3

    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'epic_bot'
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/epic
      - T_TOKEN=${T_TOKEN}
      - CHANNEL=${CHANNEL}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres:
