version: "3.9"
services:

  db:
    image: postgres:13.9-alpine
    container_name: 'epic_postgres'
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: PGPASSWORD=$POSTGRES_PASSWORD psql --username $POSTGRES_USER --dbname $POSTGRES_DB -c '\q'
      interval: 50s
      timeout: 10s
      retries: 3

    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'epic_bot'
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      TG_TOKEN: ${TG_TOKEN}
      TG_CHANNEL: ${TG_CHANNEL}
      DELAY_SEC: ${DELAY_SEC}
      TIMEOUT_SEC: ${TIMEOUT_SEC}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres:
